apiVersion: apps/v1
kind: Deployment
metadata:
  name: timber-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timber-backend  
  template:
    spec:
      containers:
      - name: timber-backend
        image: nbrown/timber-backend:8bf9118d4211a266b8d1bcb4bf3a4990b4ca9cbf
        ports:
        - containerPort: 8080
