apiVersion: apps/v1
kind: Deployment
metadata:
  name: timber-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timber-backend  
  template:
    spec:
      containers:
      - name: timber-backend
        image: nbrown/timber-backend:v1.1
        ports:
        - containerPort: 8080
